### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by Bluscream** [sloonz/wkr#1]
It says press c + y but when i do that it just types it in the password field

**Comment by sloonz** [comment]
C-y means Ctrl-Y

That being said, this project is no longer maintained. There are now great open-source, self-hostable passwords managers. I would advise to seek out alternatives like Bitwarden.

**Comment by Bluscream** [comment]
Thanks, i will take a look and as a tip you can archive this repo if its unmaintained or atleast write a hint in the readme

**Comment by Bluscream** [comment]
Thanks i will take a look
